language: node_js
node_js:
  - '10'
before_install:
  - npm install --global npm
  - npm install -g greenkeeper-lockfile@1
script:
  - npm run test
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
